---
- name: Configure the WebServers
  hosts: webservers
  remote_user: client
  become: true

  tasks:
   - name: update and upgrade apt packages
     apt:
       update_cache: yes
       upgrade: dist
       force_apt_get: yes
   - name: install nginx
     apt:
       name: nginx
       state: latest
   - name: add php7 PPA repository
     apt_repository:
       repo: 'ppa:ondrej/php'
   - name: install php7.4-fpm
     apt:
       name: php7.4-fpm
   - name: install php7.4 packages
     apt:
       name: "{{item}}"
     loop:
       - php7.4-common
       - php7.4-mysql
       - php7.4-xml
       - php7.4-xmlrpc
       - php7.4-curl
       - php7.4-gd
       - php7.4-imagick
       - php7.4-cli
       - php7.4-dev
       - php7.4-imap
       - php7.4-mbstring
       - php7.4-opcache
       - php7.4-soap
       - php7.4-zip
       - php7.4-intl
       - php7.4-pgsql
   - name: Download farmOS source file
     get_url:
       url: 'https://github.com/farmOS/farmOS/releases/download/2.0.0-alpha1/farmOS-2.0.0-alpha1.tar.gz'
       dest: /etc/nginx/
   - name: Unzips the farmOS source file
     unarchive:
       src: /etc/nginx/farmOS-2.0.0-alpha1.tar.gz
       dest: /etc/nginx/
       remote_src: True
   - name: deletes the farmOS tarball
     file:
       path: /etc/nginx/farmOS-2.0.0-alpha1.tar.gz
       state: absent
   - name: copy default file
     copy:
       src: default.conf
       dest: /etc/nginx/sites-available/farmOS
   - name: create symlink between sites-enabled/default and sites-available/default
     file: 
       src: /etc/nginx/sites-available/farmOS
       dest: /etc/nginx/sites-enabled/farmOS
       owner: root
       group: root
       state: link
       force: True
   - name: restart nginx service
     service: 
       name: nginx
       state: restarted

- name: Configure DB Servers
  hosts: databases
  remote_user: database
  become: true
  tasks:
    - name: Create repo
      lineinfile:
        path: /etc/apt/sources.list.d/pgdg.list
        line: 'deb [trusted=yes] http://apt.postgresql.org/pub/repos/apt bionic-pgdg main'
    - name: Import signing key
      shell: "wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -"
    - name: update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist
        force_apt_get: yes
    - name: install postgreSQL package
      apt:
        name: "{{item}}"
      loop:
        - postgresql-12
        - postgresql-client-12
        - postgresql-contrib-12
        - libpq-dev
        - python3-psycopg2
    - name: ensure postgres is running
      service:
        name: postgresql
        state: started
        enabled: yes
    - name: ensure that the DB can listen to external hosts
      lineinfile: 
        path: /etc/postgresql/12/main/postgresql.conf
        line: "listen_addresses='*'"
    - name: ensure that client can connect to DB
      lineinfile: 
        path: /etc/postgresql/12/main/pg_hba.conf
        insertafter: '^------------------------'
        line: 'host	all	all	192.168.56.102/24	trust'
    - name: restart postgresql service
      service: 
        name: postgresql
        state: restarted
    - name: ensure farmOS_DB is created
      become_user: postgres
      postgresql_db:
        name: 'farmOS_DB'
        encoding: 'UTF-8'
    - name: create user and allow to alter DB
      become_user: postgres
      postgresql_user:
        db: 'farmOS_DB'
        name: 'farmOS'
        password: '12345'
        role_attr_flags: CREATEDB

  
        
    

  
       
